// <auto-generated />
namespace EmployeeRecord.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class employeeRecodr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeRecodr));
        
        string IMigrationMetadata.Id
        {
            get { return "202109041903444_employeeRecodr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
